import type { ISingleOptionsField } from "@/admin/shared/types/fields.type";
import { DEFAULT_CURRENCY_SETTINGS } from "./base";

export const radioDefaults = (): Partial<ISingleOptionsField> => ({
  label: "",
  _id: null,
  default: "",
  onValue: null,
  description: "",
  required: false,
  _event: "change",
  allowRound: false,
  additionalCss: "",
  _tag: "cost-radio",
  additionalStyles: "",
  addToSummary: true,
  allowCurrency: false,
  calculateHidden: false,
  fieldCurrency: false,
  seperateCurrency: false,
  hasNextTick: true,
  nextTickCount: 0,
  disableOptions: [],
  type: "Radio Button",
  icon: "ccb-icon-Path-3511",
  alias: "radio_field_id_",
  desc_option: "after",
  summary_view: "show_value",
  styles: {
    elementColumns: "4",
    box_style: "vertical",
    style: "default",
  },
  options: [
    { optionText: "Option 1", optionValue: "10", optionHint: "" },
    { optionText: "Option 2", optionValue: "20", optionHint: "" },
    { optionText: "Option 3", optionValue: "30", optionHint: "" },
    { optionText: "Option 4", optionValue: "40", optionHint: "" },
  ],
  apply_style_for_all: false,
  width: "100",
  fieldCurrencySettings: { ...DEFAULT_CURRENCY_SETTINGS },
});
